# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  s3_access_key_id: AKIAIEBRTBBZSOFDWDLQ
  s3_secret_access_key: z1m3mxz6KihLOtYRr9SG7gpkZgfDccwQW3tzcq74

development:
  secret_key_base: a4547d2f09c6dbd04154f0008f15055f81f757d0ab11565f3952980bb0b93f670dc6cc40cb01d9230f15b68b3b294fbb1c57f324de7a2146cd8eb1c47904b849
  s3_bucket: ptv-arrival-board.development
  ptv_api_key: PTV_Loc_Infinum_BY1FII2CD
  <<: *default
test:
  secret_key_base: 2fc023418f3c019017830932c14349d6e40f9bb9d8bcc10f296bf81075e6f1e3dfd4bcf6abd0653c9614f7b66d5213623337045951733d192561040cbf5ccf4d
  s3_bucket: ptv-arrival-board.development
  ptv_api_key: PTV_Loc_Infinum_BY1FII2CD
  <<: *default
staging:
  secret_key_base: 78459040c3093c140f9bb9d8bcc10f614f7b6136243452f5c02fc023451733d10f296bf8107519256118f3c01901296bf81075e6f1e3dfd4bcf6abd0659bcf4d
  s3_bucket: ptv-arrival-board.staging
  ptv_api_key: PTV_Loc_Infinum_BY1FII2CD
  <<: *default
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket: ptv-arrival-board.production
  ptv_api_key: ''
  <<: *default
